### ISSUE TITLE
How do we run migrations using the knex migration API ?

### ISSUE THREAD

**Issue by ShivamJoker** [markusahlstrand/knex-data-api-client#69]
I tried importing the db and then calling the `knex.migrate.up` but it gave this error

```json
Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Knex: run\n$ npm install rds-data --save\n'secretArn' string value required",
    "stack": [
        "Error: Knex: run",
        "$ npm install rds-data --save",
        "'secretArn' string value required",
        "    at PostgresClientRDSDataAPI.initializeDriver (/var/task/node_modules/knex/lib/client.js:182:13)",
        "    at new Client (/var/task/node_modules/knex/lib/client.js:71:12)",
        "    at new Client_PG (/var/task/node_modules/knex/lib/dialects/postgres/index.js:18:5)",
        "    at new PostgresClientRDSDataAPI (/var/task/node_modules/knex-aurora-data-api-client/src/postgres.js:7:5)",
        "    at Function.knex (/var/task/node_modules/knex/lib/knex-builder/Knex.js:12:28)",
        "    at Object.<anonymous> (/var/task/db.js:5:19)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at Object.<anonymous> (/var/task/migrations.js:4:14)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)"
    ]
}
```

**Comment by ShivamJoker** [comment]
My bad forgot to pass the env
